### ISSUE TITLE
Ubuntu install fails at make after config

### ISSUE THREAD

**Issue by jandrieu** [airshipcloud/zephyr#5]
After installing everything and running the config script, `make` generated the following error:

`make[1]: Entering directory /home/ubuntu/respect/zephyr/cloudstore
./rebar get-deps`
`=ERROR REPORT==== 18-Feb-2013::22:40:39 ===
beam/beam_load.c(1365): Error loading module rebar:
  use of opcode 153; this emulator supports only up to 152`

`=ERROR REPORT==== 18-Feb-2013::22:40:39 ===`
`Loading of /home/ubuntu/respect/zephyr/cloudstore/rebar/rebar/ebin/rebar.beam failed: badfile
escript: exception error: undefined function rebar:main/1
  in function  escript:run/2
  in call from escript:start/1
  in call from init:start_it/1
  in call from init:start_em/1
make[1]: *** [deps] Error 127`
`make[1]: Leaving directory '/home/ubuntu/respect/zephyr/cloudstore'`
`make: *** [all] Error 2`

**Comment by simple10** [comment]
Hi Joe. You most likely have an older version of Erlang installed.

Check by running "erl" from the command line. You should have R15B03 or later.

If you don't, follow the instructions here: https://www.erlang-solutions.com/downloads/download-erlang-otp

Let us know if you run into any problems getting it to work.

**Comment by jandrieu** [comment]
Indeed. I used apt-get and ended up with R14B4. Btw, also the
squeeze-backports bit didn't work, but I was able to get postgres
anyway.

However, there is no guidance for how to set up the databases. So, I
get the following error running the init.sh

## 

psql: FATAL:  Peer authentication failed for user "postgres"

createdb: could not connect to database postgres: FATAL:  Peer
authentication failed for user "cf_cloudstore"

psql: FATAL:  Peer authentication failed for user "postgres"

psql: FATAL:  Peer authentication failed for user "cf_cloudstore"

-j

On Mon, Feb 18, 2013, at 07:05 PM, Joe Johnston wrote:

  Hi Joe. You most likely have an older version of Erlang installed.

  Check by running "erl" from the command line. You should have R15B03
  or later.

  If you don't, follow the instructions here:
  [1]https://www.erlang-solutions.com/downloads/download-erlang-otp

  Let us know if you run into any problems getting it to work.

  —

Reply to this email directly or [2]view it on GitHub.

  [-RAWYvoylBKKzlpbgRSLisXcVNdFOrjvPpj110cQM3_yveC4qhRmWNasMuvJLncL.gi
  f]

## 

Joe Andrieu

SwitchBook

joe@switchbook.com

+1(805)705-8651

References
1. https://www.erlang-solutions.com/downloads/download-erlang-otp
2. https://github.com/airships/zephyr/issues/5#issuecomment-13754622

**Comment by simple10** [comment]
The Troubleshooting wiki page covers the Postgres permission issue. https://github.com/airships/zephyr/wiki/Troubleshooting

At the moment, we're trying to keep the README file pretty lean. So it assumes a bit of familiarity with different Linux package systems and database setup.

The README only covers Debian. Ubuntu is very similar to Debian but has different package repos for apt-get. Most likely, PostgreSQL 9.1+ is already in Ubuntu's default repos. So no need to use any backports.

Just try ...
sudo apt-get install postgresql-server
sudo apt-get install postgresql-contrib

Just make sure it installs 9.1 or later.

**Comment by simple10** [comment]
I setup a clean Debian VirtualBox and documented each step required in the README
https://github.com/airships/zephyr/blob/master/README.md

I'll do CentOS and Ubuntu as well later today.

**Comment by simple10** [comment]
Install instructions have been updated for Ubuntu. Let us know if you run into any rebar compilation errors.
